# Generated by Django 5.2.1 on 2025-06-03 20:05
# apps/core/migrations/0002_cargar_catalogos.py

from django.db import migrations

def cargar_catalogos(apps, schema_editor):
    Categoria = apps.get_model('core', 'Categoria')
    MetodoPago = apps.get_model('core', 'MetodoPago')
    EstatusCotizacion = apps.get_model('core', 'EstatusCotizacion')

    # Categorías base
    categorias = ['Iluminación', 'Sonido', 'Decoración', 'Mobiliario']
    for nombre in categorias:
        Categoria.objects.create(
            nombre=nombre,
            usuario_creacion="init"
        )

    # Métodos de pago base
    metodos = ['Efectivo', 'Transferencia', 'Tarjeta de crédito', 'PayPal']
    for nombre in metodos:
        MetodoPago.objects.create(
            nombre=nombre,
            descripcion="",
            usuario_creacion="init"
        )

    # Estatus de cotización
    estatus = ['Pendiente', 'Aprobada', 'Rechazada', 'Cancelada']
    for nombre in estatus:
        EstatusCotizacion.objects.create(
            nombre=nombre,
            descripcion="",
            usuario_creacion="init"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_catalogos),
    ]

