# Generated by Django 5.2.1 on 2025-06-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('usuario_creacion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_actualizacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
