# Generated by Django 5.2.1 on 2025-06-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url_imagen',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
